MemoryCards/Models/CardManagerContext.cs
using Microsoft.EntityFrameworkCore;

namespace MemoryCards.Models
{
    public class CardManagerContext : DbContext
    {
        public CardManagerContext(DbContextOptions<CardManagerContext> options) : base(options)
        {
        }
        public DbSet<CardModel> Cards { get; set; }
    }
}

MemoryCards/Models/CardModel.cs
using System.ComponentModel.DataAnnotations;

namespace MemoryCards.Models

{
    public class CardModel
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }

        public bool IsKnown { get; set; }
        public int level { get; set; }

        public bool FirstAttemp { get; set; }


    }
}

MemoryCards/Models/CardTempManagerContext.cs
using Microsoft.EntityFrameworkCore;

namespace MemoryCards.Models
{
    public class CardTempManagerContext : DbContext
    {
        public CardTempManagerContext( DbContextOptions options) : base(options)
        {
        }
        public DbSet<CardModel> CardsTemp { get; set; }
    }
}

MemoryCards/Controllers/CardsController.cs
using MemoryCards.Models;
using MemoryCards.Repositories;
using MemoryCards.Services;
using Microsoft.AspNetCore.Mvc;

namespace MemoryCards.Controllers
{
    public class CardsController : Controller
    {
        private readonly ICardRepository _cardRepository;
        private ICardTempRepository _cardTempRepository;
        private readonly ICardService _service;
        
        public CardsController(ICardService service, ICardRepository cardRepository, ICardTempRepository cardTempRepository)
        {
            _service = service;
            _cardRepository = cardRepository;
            _cardTempRepository = cardTempRepository;
        }

        public ActionResult Mainy()
        {
            
            var chosenCard = _service.Mainy(_cardTempRepository.GetAll());
            if (chosenCard == null)
            {
                return View("Gratulation");
            }
            else
            {
                return View(chosenCard);
            }

        }
        public ActionResult Index()
        {
            var result = _service.ShuffleTen(_cardRepository.GetAll());
            _cardTempRepository.Convert(result);
            return View(_cardRepository.GetAll());
        }


        public ActionResult Details(int id)
        {
            return View(_cardRepository.Details(id));
        }


        public ActionResult Create()
        {
            return View(new CardModel());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CardModel cardModel)
        {

            _cardRepository.Add(cardModel);
            return RedirectToAction(nameof(Index));
        }


        public ActionResult Edit(int id)
        {
            return View(_cardRepository.Get(id));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CardModel cardModel)
        {
            _cardRepository.Update(id, cardModel);
            return RedirectToAction(nameof(Index));

        }


        public ActionResult Delete(int id)
        {

            return View(_cardRepository.Get(id));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, CardModel cardModel)
        {
            _cardRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult Know(int id)
        {
            _cardTempRepository.Know(id);
            _cardRepository.Know(id);
            return RedirectToAction(nameof(Mainy));
        }

        [HttpPost]
        public ActionResult DontKnow(int id)
        {
            _cardRepository.DontKnow(id);
            return RedirectToAction(nameof(Mainy));
        }
    }
}

MemoryCards/Views/Cards/Create.cshtml
@model MemoryCards.Models.CardModel

@{
    ViewData["Title"] = "Create";
}


<style >
    body {
        background-color: #0e192b;
        color: #fff;
         }
</style >

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" style="display: inline;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Question" class="control-label"></label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Answer" class="control-label"></label>
                <input asp-for="Answer" class="form-control" />
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
            <a class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </a>
           
        </form>
    <a asp-action="Index" class="btn btn-secondary">Back to list </a>
    </div>
</div>


   

MemoryCards/Views/Cards/Delete.cshtml
@model MemoryCards.Models.CardModel

@{
    ViewData["Title"] = "Delete";
}


<style >
    body {
        background-color: #0e192b;
        color: #fff;
         }
</style >

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CardModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Answer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Answer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.level)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> 

        <a asp-action="Index" class="btn btn-secondary">Back to list </a>
    </form>
</div>

MemoryCards/Views/Cards/Details.cshtml
@model MemoryCards.Models.CardModel

@{
    ViewData["Title"] = "Details";
}

<style >
    body {
        background-color: #0e192b;
        color: #fff;
         }
</style >

<div>
    <h4>CardModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Answer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Answer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsKnown)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsKnown)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.level)
        </dd>
    </dl>
</div>
<div>
    <a method="post" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
            
 
    <a asp-action="Index" class="btn btn-secondary">Back to list </a>
</div>

MemoryCards/Views/Cards/Edit.cshtml
@model MemoryCards.Models.CardModel

@{
    ViewData["Title"] = "Edit";
}


<style >
    body {
        background-color: #0e192b;
        color: #fff;
         }
</style >

<h1>Edit</h1>

<h4>CardModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Question" class="control-label"></label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Answer" class="control-label"></label>
                <input asp-for="Answer" class="form-control" />
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
                   
            <a asp-action="Index">
                <input type="submit" value="Save" class="btn btn-primary" />
            </a>
            <a asp-action="Index" class="btn btn-secondary">Back to list </a>
        </form>
          
                 
          
    </div>
</div>


           

MemoryCards/Views/Cards/Gratulation.cshtml
@{
    ViewData["Title"] = "Gratulation";
}

<style >
    body {
        background-color: #0e192b;
        color: #fff;
         }
</style >

<h1>Gratulation</h1>

<a asp-action="Index" class="btn btn-secondary">Back to list </a>

MemoryCards/Views/Cards/Index.cshtml
@model IEnumerable<MemoryCards.Models.CardModel>

@{
    ViewData["Title"] = "Index";
}

<style >
    body {
        background-color: #0e192b;
        color: #fff;
         }
</style >



<h1 style="text-align: center;">All Your MemoryCards</h1>

             <a asp-action="Create">
              <input type="submit" value="Create new" class="btn btn-outline-primary"/>
             </a>

             <a asp-action="Mainy" >
              <input type="submit" value="Start Learning" class="btn btn-outline-success"/>
             </a>
          <br/>
     
    

<table style=" margin-top: 10px;" class="table table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Question)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Answer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsKnown)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.level)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Question)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsKnown)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.level)
            </td>
            <td style="width: 250px;">
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id } , new {@class = "btn btn-outline-warning"} ) 
                @Html.ActionLink("Details", "Details", new {  id=item.Id  }, new {@class = "btn btn-outline-info"}) 
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  }, new {@class = "btn btn-outline-danger"})
                
            </td>
        </tr>
}
    </tbody>
</table>
   

MemoryCards/Views/Cards/Mainy.cshtml
@model MemoryCards.Models.CardModel

@{
    ViewData["Title"] = "Mainy";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script>
        function showDiv() {
            document.getElementById('KnowOrNot').style.display = "block";
            document.getElementById('ShowButton').style.display = "none";
        }
</script>


<style >
    body {
        background-color: #0e192b;
        color: #fff;
         }

    tr{
        text-align: center;
    }
</style >

<table class="table table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Question)             
            </th>
         
        </tr>
    </thead>


    <tr>
            <td>
                @Html.DisplayFor(model => model.Question)
            </td>
    </tr>
</table> 
         <div id="KnowOrNot" style="display: none;">

            <table class="table table-dark">
              <thead>
                  <tr>        
                      <th>
                         @Html.DisplayNameFor(model => model.Answer)               
                     </th>
                 </tr>


                 <tr>
                      <td>
                         @Html.DisplayFor(model => model.Answer)
                     </td>                  
                 </tr>
               </thead>
            </table>

                <div style="align-items: center;">
                     <form method="post" asp-action="Know" asp-route-id="@Model.Id" >
                     <input type="submit" value="Know" class="btn btn-success" /> 
                </form>

                    <br/>
                 <form method="post" asp-action="DontKnow" asp-route-id="@Model.Id" >
                     <input type="submit" value="Dont Know" class="btn btn-primary"  />    
                 </form> 

                </div>
                
                  
                
         </div>

          
          <a id="ShowButton" href="javascript:;" onclick="showDiv()" class="btn btn-info" style="margin-bottom: 15px;">Show</a>
          <br/>
           <a asp-action="Index" class="btn btn-secondary">Back to list </a>
          

         

         

        
   

MemoryCards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MemoryCards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav style="background-color: #47a6b3;"class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Cards" asp-action="Index">MemoryCards</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cards" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cards" asp-action="Mainy">Learn</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2022 - Jarzq - <a href="https://github.com/Jarzq" target="blank">Github</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>